### ISSUE TITLE
this looks interesting

### ISSUE THREAD

**Issue by dominictarr** [sidorares/abstractsocket#1]
what is it for? how does an abstract socket differ from a regular socket?

**Comment by sidorares** [comment]
http://www.kernel.org/doc/man-pages/online/pages/man7/unix.7.html

DBus by default uses abstract sockets namespace ( on my ubuntu box DBUS_SESSION_BUS_ADDRESS is something lite "unix:abstract=/tmp/dbus-L4fFfELPkU" and I'm using it to transparently wrap `socat abstract-client:/tmp/dbus-L4fFfELPkU -`

I didn't realise this is possible to do using duplex/event-stream until yesterday, but default behaviour of module is more specific to my problem - make net.createConnection('\u0000somename') to connect to abstract unix socket. Real support involves some changes in node/src/pipe_wrap.cc and libuv, which I'm planning to implement and submit at some time.
