### ISSUE TITLE
functionality now included in core

### ISSUE THREAD

**Issue by georgir** [sidorares/abstractsocket#4]
I have tested on node 0.10 and 0.12; in 0.12 the core net library correctly listens and also connects to paths starting with '\0', so it seems this module is now redundant. It would be nice if a note to that effect is included in the front page of this project - it is only useful for 0.10 and below.

**Comment by sidorares** [comment]
thanks, I'll try to check and add to readme

**Comment by sidorares** [comment]
I don't think you are right @georgir . Testing this:

``` js
var addr = '\u0000test';

var coreNet=false;

if (coreNet) {
  var net = require('net');
  var s = net.connect(addr);
  s.on('data', (chunk) => console.log(chunk));
  s.write('test core net');
} else {
  var abs = require('abstract-socket');
  var client = abs.connect(addr);
  client.write('test test test');
  client.on('data', (data) => console.log(data.toString()));
}
```

works fine using abstract-socket and fails to connect using core net. abstract socket server via `socat ABSTRACT-LISTEN:test STDIO` command in another terminal

Can you post your tests?

**Comment by georgir** [comment]
Ah you are right. I tested only that net.createServer(...).listen('\0test') did not create ' test' file, and was connectable by net.connect('\0test'). 
It seems it does indeed create/connect to an abstract unix socket... but its name is still misinterpreted. it is listed as just "@" in lsof and net.connect('\0anything') connects to it.
